[project]
name = "vqca"
version = "0.0.1"
authors = [
  { name="Petrônio Cândido de Lima e Silva", email="petronio.candido@ifnmg.edu.br" }
]
description = "Variational Quantum Cellular Automata"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy",
  "matplotlib",
  "pandas",
  "qiskit",
  "qiskit-aer",
  "pylatexenc",
  "torch",
  "deap",
  "cma",
  "qiskit_algorithms"
]

[tool.setuptools.packages.find]
include = ["vqca*"] 

[project.urls]
Homepage = "https://github.com/petroniocandido/VQCA/"
Issues = "https://github.com/petroniocandido/VQCA/issues"
